## Terror Attack

It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period.

#### Problem Statement:
Find out the Country with Highest Number of Terror Attack and in  which year the most number of terrorist attack happened in that Country?<br>
<br>
Print count of terror attacks as integer value.<br>

#### Output Format:
Country  NumberOfAttack   Year

In [1]:
# Importing the libraries
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('terrorismData.csv')

In [4]:
# making the copy of the dataset
df = dataset.copy()
df

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,2017,12,31,Somalia,Middle Shebelle,Sub-Saharan Africa,Ceelka Geelow,2.359673,45.385034,Armed Assault,1.0,2.0,Checkpoint,12/31/2017: Assailants opened fire on a Somali...,Al-Shabaab,Military,Firearms
181687,2017,12,31,Syria,Lattakia,Middle East & North Africa,Jableh,35.407278,35.942679,Bombing/Explosion,2.0,7.0,Hmeymim Air Base,12/31/2017: Assailants launched mortars at the...,Muslim extremists,Military,Explosives
181688,2017,12,31,Philippines,Maguindanao,Southeast Asia,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,0.0,0.0,Houses,12/31/2017: Assailants set fire to houses in K...,Bangsamoro Islamic Freedom Movement (BIFM),Private Citizens & Property,Incendiary
181689,2017,12,31,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives
181690,2017,12,31,Philippines,Maguindanao,Southeast Asia,Cotabato City,7.209594,124.241966,Bombing/Explosion,0.0,0.0,Unknown,12/31/2017: An explosive device was discovered...,Unknown,Unknown,Explosives

In [5]:
# Extracting the Country from the dataset in which there is highest number of Terror Attack
df1 = df.Country.describe().top 
df1

'Iraq'

In [27]:
country = df1
country

'Iraq'

In [8]:
# Extracting the part of the dataset for that Country only
df_iraq = df[df['Country'] == 'Iraq']
df_iraq

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
2854,1975,3,1,Iraq,Nineveh,Middle East & North Africa,Mosul,36.354145,43.143570,Hijacking,0.0,1.0,B-737,NaN,Unknown,Airports & Aircraft,Unknown
4385,1976,12,15,Iraq,Baghdad,Middle East & North Africa,Baghdad,33.303566,44.371773,Bombing/Explosion,10.0,285.0,Airport terminal,NaN,Unknown,Airports & Aircraft,Explosives
4393,1976,12,18,Iraq,Unknown,Middle East & North Africa,Penjwon,NaN,NaN,Hostage Taking (Kidnapping),0.0,0.0,agricultural experts in NE Iraq,NaN,Kurdish Democratic Party-Iraq (KDP),Government (General),Unknown
4402,1976,12,24,Iraq,Baghdad,Middle East & North Africa,Baghdad,33.303566,44.371773,Assassination,2.0,0.0,Personnel,NaN,Unknown,Violent Political Party,Firearms
8688,1979,6,15,Iraq,Basra,Middle East & North Africa,Basra,30.510054,47.778095,Assassination,1.0,0.0,local secretary,NaN,Unknown,Government (General),Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181669,2017,12,30,Iraq,Kirkuk,Middle East & North Africa,Kirkuk,35.452110,44.375465,Bombing/Explosion,0.0,5.0,Cafe,12/30/2017: Assailants threw grenades at a caf...,Unknown,Business,Explosives
181670,2017,12,31,Iraq,Diyala,Middle East & North Africa,Hawd al-Waqf,33.816111,44.783524,Unknown,1.0,0.0,Station,12/31/2017: Assailants attacked a police stati...,Islamic State of Iraq and the Levant (ISIL),Police,Unknown
181671,2017,12,31,Iraq,Saladin,Middle East & North Africa,Farhatiyah,34.031331,44.070106,Bombing/Explosion,4.0,9.0,Civilians,12/31/2017: Assailants attacked civilians in F...,Islamic State of Iraq and the Levant (ISIL),Private Citizens & Property,Explosives
181674,2017,12,31,Iraq,Nineveh,Middle East & North Africa,Baaj,36.045059,41.716717,Unknown,5.0,0.0,Troops,"12/31/2017: Assailants attacked Baaj, Nineveh,...",Islamic State of Iraq and the Levant (ISIL),Military,Unknown
181679,2017,12,31,Iraq,Diyala,Middle East & North Africa,Muqdadiyah,33.953167,44.921906,Armed Assault,13.0,0.0,Post,12/31/2017: Assailants attacked volunteer figh...,Islamic State of Iraq and the Levant (ISIL),Military,Firearms

In [26]:
# Creating the dataframe of the year description
year_df = pd.DataFrame({'Year Description': df_iraq.Year.describe()})
year_df

       Year Description
count      24636.000000
mean        2012.477107
std            3.894405
min         1975.000000
25%         2010.000000
50%         2014.000000
75%         2015.000000
max         2017.000000

In [34]:
# Extracting the count from the dataframe
count = year_df.loc['count', 'Year Description']
count = int(count)
count

24636

In [36]:
# exatracting the year from the dataframe
max_year = year_df.loc['max', 'Year Description']
max_year = int(max_year)
max_year

2017

In [40]:
print('Country \t NumberOfAttack \t Year')
print(country,'\t\t\t', count,'\t\t', max_year)

Country 	 NumberOfAttack 	 Year
Iraq 			 24636 		 2017

In [42]:
# Creating the above ouput as a dataframe
data = {'Country':country, 'Number of Attack':count, 'Year':max_year}
answer = pd.DataFrame(data, index=[0])
answer

  Country  Number of Attack  Year
0    Iraq             24636  2017